name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: |
          go mod download
          go build -v ./...

      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          if [ -z "$RENDER_API_KEY" ] || [ -z "$RENDER_SERVICE_ID" ]; then
            echo "Missing Render secrets. Set RENDER_API_KEY and RENDER_SERVICE_ID in repo secrets."
            exit 1
          fi

          # Test API key quickly (optional debug)
          echo "Listing services (quick API key check)..."
          curl -sS -H "Accept: application/json" -H "Authorization: Bearer ${RENDER_API_KEY}" \
            "https://api.render.com/v1/services?limit=1" || true

          # Trigger deploy — use string value for clearCache per docs
          response=$(curl -sS -w "\n%{http_code}" -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            --data-raw '{"clearCache":"do_not_clear"}')

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "HTTP status: $http_code"
          echo "Response body: $body"

          if [ "$http_code" -ge 400 ]; then
            echo "Render deploy failed"
            exit 1
          fi